### PR TITLE
implement drop database

### PR DESCRIPTION
**Pull request by Dikaeinstein**
#### What does this PR do?
Implement drop database
#### Description of Task to be completed?
  - add drop.js file which contains logic to drop db
  - add the dropDatabase function to the mongoBackend
  - bind the drop database functionality to cli.js and index.js
#### How should this be manually tested?
You can either drop db from the cli using this ```dbclone drop --host {hostIp} --db {dbName}``` or drop into interactive mode by just running ```dbclone``` and selecting the drop mode.

### CODE REVIEW

**Comment by Dikaeinstein** [comment]
@vot The PR for drop database is up. Review and merge, if you consider it good enough. Feedback is always welcomed.

**Comment by vot** [comment]
Hi @Dikaeinstein,

It looks pretty good, I just have a few suggestions/questions.
Not sure if you've seen my responses in the PR so I thought I'd tag you here.

**Comment by Dikaeinstein** [comment]
Thanks for the feedback @vot, will implement the feedback and update the PR.

**Comment by Dikaeinstein** [comment]
I've updated the PR. No more yarn.lock.

**Pull request merged**
