### PR TITLE
Add backends documentations

### PR DESCRIPTION
**Pull request by martalais**
Add some comments at the fs.js and mongo.js, at the backend package.

### CODE REVIEW

**Comment by martalais** [comment]
Done! :)

**Comment by vot** [comment]
I'm still seeing the old comments - have you pushed the branch? :)

**Comment by martalais** [comment]
yes, that's strange...
can you tell me the git command? maybe i'm doing it wrong

**Comment by vot** [comment]
It should be simply `git push` while you're on the branch.
After this the commit should appear in the listing of this PR.

You may want to hit `git status` to see whether all the changes are committed and pushed ;)

**Comment by vot** [comment]
Closing as the comments are pretty redundant and simply describe what each line is doing.
There are some JSDoc comments in the code which also explain usage and context - that's the style to follow.

**Pull request closed without merging**
